name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main
      
env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: 42nomad-deploy
  AWS_CODE_DEPLOY_APPLICATION: github-action-deploy
  AWS_CODE_DEPLOY_GROUP: github-action-deploy

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    steps:
    - name: main 브랜치로 이동
      uses: actions/checkout@v3
    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.SUBMODULE_TOKEN }}
    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
#    - name: 시크릿 값 환경 변수로 설정
#        run: |
#          echo "${{ secrets.APPLICATION_ENV }}" > application.yml
#      working-directory: ./src/main/resources/
    - name: gradlew에 실행 권한 부여
      run: | 
        source $GITHUB_ENV
        chmod +x ./gradlew
    - name: 프로젝트 빌드
      run: ./gradlew clean customBuild -x test
    - name: AWS credential 설정
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
    - name: S3에 업로드
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/cicdtest/$GITHUB_SHA.zip --source .
    - name: EC2에 배포
      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=cicdtest/$GITHUB_SHA.zip,bundleType=zip
